shared:
  image: node:lts
jobs:
    main:
        steps:
            - echo: echo 'this is test job.'
        requires: [~commit, ~pr]
    jobA:
        requires: [~pr-closed]
        steps:
            - fork-step: echo "this is fork step"
            - echo: |
                echo 'this job is executed when a pr is closed/merged.'
            - meta: meta get sd.pr
    jobB:
        requires: [~pr, ~pr-closed]
        steps:
            - echo: |
                echo 'this job is executed when a pr is created or it is closed/merged.'
            - meta: meta get sd.pr 
    jobC:
        requires: [~pr-closed:stable, ~pr:stable]    
        steps:
            - echo: |
                echo 'this job is executed when a pr is closed/merged on branch stable.'
            - meta: meta get sd.pr
